PREFIX obot: <https://w3id.org/onto-bot#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX ex: <http://example.org/data/>

SELECT DISTINCT ?obj WHERE {
  ?obj a obot:Object ;
    dul:hasLocation ?loc .
  ?loc a obot:CurrentLocation ;
    obot:onTopOf ex:Counter .
}