PREFIX obot: <https://w3id.org/onto-bot#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX ex: <http://example.org/data/>
PREFIX example: <http://example.com/ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?action ?actionLabel ?targetObj ?targetLabel ?follows ?followsLabel ?precedes ?precedesLabel WHERE {
  {
    ?obj a obot:Object ;
         rdfs:label ?objLabel ;
         dul:hasLocation ?loc .
    ?loc a obot:CurrentLocation ;
         obot:onTopOf ex:Counter .

    ?action a dul:Action ;
            rdfs:label ?actionLabel ;
            obot:actsOn ?targetObj .
    ?targetObj rdfs:label ?targetObjLabel .
    OPTIONAL { ?action obot:follows ?follows . ?follows rdfs:label ?followsLabel . }
    OPTIONAL { ?action obot:precedes ?precedes . ?precedes rdfs:label ?precedesLabel . }
    BIND(?objLabel AS ?targetObjLabel)
  }
  UNION
  {
    ?linkedAction a dul:Action ;
                  obot:actsOn ?linkedObj ;
                  rdfs:label ?linkedLabel .
    {
      ?linkedAction obot:follows ?action .
    } UNION {
      ?linkedAction obot:precedes ?action .
    }

    ?action a dul:Action ;
            rdfs:label ?actionLabel ;
            obot:actsOn ?targetObj .
    OPTIONAL { ?action obot:follows ?follows . ?follows rdfs:label ?followsLabel . }
    OPTIONAL { ?action obot:precedes ?precedes . ?precedes rdfs:label ?precedesLabel . }
    OPTIONAL { ?targetObj rdfs:label ?targetLabel . }
}
}